// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0qBDefV1pVTD3pyKUs2Y54iHtXxWSGBE',
    appId: '1:927964269504:web:370c8f473de7cfeb47d625',
    messagingSenderId: '927964269504',
    projectId: 'onyswap-org',
    authDomain: 'onyswap-org.firebaseapp.com',
    storageBucket: 'onyswap-org.appspot.com',
    measurementId: 'G-YLBZ4ZW6FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLL6_ndkoN8cf0xS5np__bcvCAaJtPlQk',
    appId: '1:927964269504:android:dd7ec0e582b2080e47d625',
    messagingSenderId: '927964269504',
    projectId: 'onyswap-org',
    storageBucket: 'onyswap-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAEl0Kolg4Y55xIM6qK67ir0kUYe8nQ7o',
    appId: '1:927964269504:ios:e046aa9a7d3f832547d625',
    messagingSenderId: '927964269504',
    projectId: 'onyswap-org',
    storageBucket: 'onyswap-org.appspot.com',
    iosClientId: '927964269504-jdsa0kf6dciab0t1eb8dbajkmkagisqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.onyxswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAEl0Kolg4Y55xIM6qK67ir0kUYe8nQ7o',
    appId: '1:927964269504:ios:e046aa9a7d3f832547d625',
    messagingSenderId: '927964269504',
    projectId: 'onyswap-org',
    storageBucket: 'onyswap-org.appspot.com',
    iosClientId: '927964269504-jdsa0kf6dciab0t1eb8dbajkmkagisqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.onyxswap',
  );
}
